Added support for createOrFirst() methode added in Laravel v10.20
larastan/larastan pull request #1740
Opened 2023-09-19 13:07 UTC by RemCom

- [x] Added or updated tests
- [ ] Documented user facing changes

**Changes**

Added support for `createOrFirst()` methode added in Laravel v10.20

**Breaking changes**

None

2023-09-19 15:39 UTC, canvural requested changes

2023-09-19 15:39 UTC, canvural commented on stubs/common/BelongsToMany.stub
The `common` folder is for files that are same for Laravel 10.x and lower versions. I don't think `createOrFirst` method is in 9.x, so this should not be here. Instead it should go to `10.0.0` folder.

2023-09-19 15:39 UTC, canvural commented on stubs/common/HasOneOrMany.stub
Same for this one.

2023-09-19 15:39 UTC, canvural commented on tests/Type/data/model-relations.php
> +    assertType('App\Account', $user->accounts()->createOrFirst([]));
Like you can see in the Github Actions this and other tests you added will fail in 9.x

So, you'd need to create a new file, for example `model-relations-l10` and then conditionally include it in `GeneralTypeTest`

2023-09-19 18:59 UTC, RemCom commented
@canvural The requested changes are implemented. The new test for `createOrFirst()` is now only included for Laravel v10.20.0 or higher

2023-09-19 19:05 UTC, szepeviktor approved these changes

2023-12-29 15:14 UTC, closed without merging

2023-12-30 00:33 UTC, nunomaduro commented
We've closed the `master` branch. Please open a new pull request and target the `2.x` branch if you wish to re-open this pull request.