Improve type inference surrounding Arr::get and Arr::pull.
larastan/larastan pull request #1858
Opened 2024-02-15 18:06 UTC by mad-briller

**Changes**

Improves type inference surrounding `Arr::get` and `Arr::pull`, such as return types and type-specifying the `Arr::pull` `$array` argument. 

Also provides a rule to alert when the `$key` is not present on the `$array` for both `Arr::get` and `Arr::pull`, closing: https://github.com/larastan/larastan/issues/1727

2024-02-15 18:17 UTC, calebdw commented on tests/Type/GeneralTypeTest.php
> +        yield from self::gatherAssertTypes(__DIR__.'/data/arr-get.php');
I would put this in the list above right after `application-make`---no need to list it after all the conditionals

2024-02-15 18:23 UTC, mad-briller commented
The static analysis actions failure is because i'm checking `$type->isObject()->yes()` before using `->isInstanceOf()` [as phpstan suggests](https://github.com/phpstan/phpstan-src/blob/1.11.x/src/Rules/Api/ApiInstanceofTypeRule.php#L73) instead of `instanceof ObjectType` but it doesn't seem to correctly infer that means it's an `ObjectType`?

2024-02-15 19:17 UTC, szepeviktor approved these changes

2024-02-15 19:20 UTC, mad-briller commented on tests/Type/GeneralTypeTest.php
> +        yield from self::gatherAssertTypes(__DIR__.'/data/arr-get.php');
sure! also wanted to say great work on the prs recently mate

2024-02-20 22:58 UTC, canvural requested changes

2024-02-20 22:58 UTC, canvural commented on src/Rules/ArrGetPullRule.php
> +        $methodName = $node->name->name;
```suggestion
        $methodName = strtolower($node->name->name);
```

2024-02-20 22:58 UTC, canvural commented on tests/Rules/data/arr-get-pull.php
> +
Can we add a test with regular arrays? Like `Arr::get([1,2,3], 4)`

2024-02-20 22:58 UTC, canvural commented on tests/Rules/data/arr-get-pull.php
> +
Also maybe with a array shape from PHPDocs.

2026-08-28 11:05 UTC, canvural commented
Thanks for the contribution. I’m closing this pull request because it targets the unmaintained `2.x` branch. If you’d still like this change to be considered, please open a new pull request targeting the `3.x` branch.

2026-08-28 11:05 UTC, closed without merging